### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by yjl9903** [yjl9903/epubook#5]
## core

+ [x] Generate abstract container (`mimetype`, `META-INFO/container.xml`)
+ [x] Generate package document
+ [ ] Generate more opf meta info
+ [x] Generate spine
+ [x] Generate navigation document
+ [x] Generate navigation document with class / style
+ [ ] Generate navigation document containing itself
+ [ ] ~~Support legacy ncx toc~~
+ [x] Bundle into a epub
+ [ ] Support fonts
+ [ ] File system?

## builder

+ [ ] Extract builder from core to this package

## Loader

+ [ ] Load the epub

## theme-default

+ [x] Page templates
+ [x] Global styles
+ [ ] Check input encode
+ [ ] Insert images utils

## epubook

+ [x] Theme integration
+ [x] Extend theme
+ [ ] Abstract dir structure
+ [ ] Per page style
+ [ ] Book option

# cli

+ [ ] Read yaml config file
+ [ ] Parse markdown content file
+ [ ] Use theme to generate epub
